[package]
name = "common"
edition.workspace = true
publish.workspace = true
version.workspace = true

[features]
default = []
openapi = ["utoipa"]

[dependencies]
axum = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
validator = { workspace = true, features = ["derive"] }
mime = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["fs", "io-util"] }
chrono = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
sea-orm = { workspace = true, features = ["macros"] }
anyhow = { workspace = true }
tracing = { workspace = true }
utoipa = { workspace = true, features = ["macros"], optional = true }
jsonwebtoken = { workspace = true }
argon2 = { workspace = true, features = ["rand"] }
rand_core = { version = "0.6", features = ["getrandom"] }
