[package]
name = "middleware"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
axum = { workspace = true }
http = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
common = { path = "../common" }
kernel = { path = "../kernel" }
metrics = { workspace = true }
http-body-util = { workspace = true }
